services:
  terabox-bot:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: terabox-bot

    restart: unless-stopped

    env_file:
      - .env

    network_mode: host

    volumes:
      - terabox_data:/app/data

    shm_size: "1gb"

volumes:
  terabox_data: